services:
  backend:
    build: ./backend
    ports:
      - '5000:5000'
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./uploads:/app/uploads 
    environment:
      NODE_ENV: ${NODE_ENV}
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ${DEV_DB_NAME} # Default to development DB
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
    depends_on:
      - database
    entrypoint: >
      sh -c "
      npm run sync-db 
      && npm run dev
      "

  frontend:
    build: ./frontend
    ports:
      - '3001:3001'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV}
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true

  database:
    image: postgres:16.4
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ${DEV_DB_NAME} # Default to development DB
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
