name: Frontend CI

on:
  push:
    paths:
      - 'frontend/**/*.js'
      - 'frontend/**/*.jsx'
      - 'frontend/**/*.ts'
      - 'frontend/**/*.tsx'
      - 'frontend/package.json'
      - 'frontend/package-lock.json'
  pull_request:
    paths:
      - 'frontend/**/*.js'
      - 'frontend/**/*.jsx'
      - 'frontend/**/*.ts'
      - 'frontend/**/*.tsx'
      - 'frontend/package.json'
      - 'frontend/package-lock.json'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Dependencies
        run: npm install --prefix frontend
      - name: Run Tests
        run: npm run test --prefix frontend
      # Uncomment the following lines if you want to upload coverage reports to Codecov
      # - name: Upload coverage reports to Codecov
      #   uses: codecov/codecov-action@v4.0.1
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     slug: ideaSquared/pet-adoption
